### ISSUE TITLE
Editor fails to write the integer for the length of objects in the gate file.

### ISSUE THREAD

**Issue by JsonX05** [RainbowUnicorn7297/thumper-modding-tool#2]
This is the line it's failing on in the editor source code.

write_int(len(obj['boss_patterns']))

When attempting to compile the code, the editor gives us a message.
File 'levels.py', line 228, in write_gate_comp
TypeError: write_int() missing 1 required positional argument: 'val'

We're not sure if it's an issue with our format as we had no template to go by, however after receiving help from many coders, I think it's an error with the editor. However, below is our current format. Please help us!

[
{
'obj_type': 'SequinGate',
'obj_name': 'spiralboss.gate',
'spn_name': 'boss_spiral.spn',
'param_path': 'boss_gate_pellet.ent',
'param_path_hash': 'c7c056e2',
'boss_patterns': [
    {
	'node_name_hash': '0c3025e2',
    'lvl_name': '1_track.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0,
    },
	{
	'node_name_hash': '27e9f06d',
    'lvl_name': '2_thumps.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0,
    },
    ], #only two levels as a test
'pre_lvl_name': '5_millipedes.lvl',
'post_lvl_name': '6_sentries.lvl',
'restart_lvl_name': 'win.lvl',
'section_type': 'SECTION_BOSS_MINI',
'random_type': 'LEVEL_RANDOM_NONE'
},
]

**Comment by RainbowUnicorn7297** [comment]
Fixed in v1.0.1.
