### ISSUE TITLE
Pyramid Boss Ending Sequence

### ISSUE THREAD

**Issue by ZetaSM** [RainbowUnicorn7297/thumper-modding-tool#4]
Hey, I've been creating a much more modern take on custom levels recently and am hoping to have figured out the ending sequence by the end of it. I'm doing some testing now to try to get it to work. I've traced back the ending_sequence ent, spn, and defined those in the gate file, and much more, but can't seem to get a grip of this.

Any instruction or insight on what I should be doing to get this to work? Thanks.

**Comment by RainbowUnicorn7297** [comment]
The pyramid boss and the ending sequence should work if you define the .gate objects in the same way as Level 9. The most probable causes for them not working are incorrect node name hashes or wrong number of boss patterns.
For pyramid.gate:
```python
[
{
'obj_type': 'SequinGate',
'obj_name': 'pyramid.gate',
'spn_name': 'gate_pyramid.spn',
'param_path': 'crakhed.ent',
'boss_patterns': [
    {
    'node_name_hash': '0c3025e2',
    'lvl_name': 'pyramid1.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0
    },
    {
    'node_name_hash': '27e9f06d',
    'lvl_name': 'pyramid2.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0
    },
    {
    'node_name_hash': '3c5c8436',
    'lvl_name': 'pyramid3.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0
    },
    {
    'node_name_hash': '6b39151f',
    'lvl_name': 'pyramid4.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0
    },
    {
    'node_name_hash': '07f819c9',
    'lvl_name': 'outro_pyramid.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0
    }
    ],
'pre_lvl_name': 'intro_pyramid.lvl',
'post_lvl_name': 'pyramid_post_intro.lvl',
'restart_lvl_name': 'pyramid_restart_intro.lvl',
'section_type': 'SECTION_BOSS_PYRAMID',
'random_type': 'LEVEL_RANDOM_NONE'
}
]
```
For ending_sequence.gate:
```python
[
{
'obj_type': 'SequinGate',
'obj_name': 'ending_sequence.gate',
'spn_name': 'ending_sequence.spn',
'param_path': 'ending_sequence.ent',
'boss_patterns': [
    {
    'node_name_hash': '0c3025e2',
    'lvl_name': 'finish.lvl',
    'sentry_type': 'SENTRY_NONE',
    'bucket_num': 0
    }
    ],
'pre_lvl_name': 'spacer_4.lvl',
'post_lvl_name': 'spacer_4b.lvl',
'restart_lvl_name': '',
'section_type': 'SECTION_BOSS_TRIANGLE',
'random_type': 'LEVEL_RANDOM_NONE'
}
]
```

**Comment by ZetaSM** [comment]
I see, so the ending sequence acts as a boss level? When defining those in the master sequin would I simply place the ending sequence after the pyramid and set checkpoint to False in the pyramid module?

**Comment by ZetaSM** [comment]
Also, what would the hashes be for where you put 'Level 0', 'Level 1', etc.. For both pyramid and ending sequence gates.

**Comment by ZetaSM** [comment]
Alright, ignore the previous two comments. I've gotten the boss to work, death and end sequence. However, it appears the end sequence takes forever to actually come up on the screen. Any way to speed up that process?

**Comment by RainbowUnicorn7297** [comment]
If the ending sequence takes longer to show up compared with the original Level 9, the problem probably lies in the number of beats in one of your .lvl/.leaf objects. Here are the number of beats for the last few .lvl objects in Level 9.
outro_pyramid.lvl: 32
spacer_4.lvl: 4
spacer_4b.lvl: 4
finish.lvl: 192
If you want to speed up the ending sequence animation itself without changing the sequin_speed, you'd need to change the objects in boss/ending_sequence.objlib, which isn't supported by the modding tool at the moment.
